// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIFJmzE7vcjjIGu4WSQFEbLqY43hnHT8',
    appId: '1:1086543133004:web:bdf52002cf1cf2208cb7e9',
    messagingSenderId: '1086543133004',
    projectId: 'eproject-8a023',
    authDomain: 'eproject-8a023.firebaseapp.com',
    storageBucket: 'eproject-8a023.firebasestorage.app',
    measurementId: 'G-WQQXL9HZHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2wFB1DxAWSdji8XcgzfjfCFO45ctjwg',
    appId: '1:1086543133004:android:3018f588b66991fc8cb7e9',
    messagingSenderId: '1086543133004',
    projectId: 'eproject-8a023',
    storageBucket: 'eproject-8a023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoLv3scG3IcTcd0ZYdeFYSHaxhqCbZp7w',
    appId: '1:1086543133004:ios:f56d354c94a598a88cb7e9',
    messagingSenderId: '1086543133004',
    projectId: 'eproject-8a023',
    storageBucket: 'eproject-8a023.firebasestorage.app',
    iosBundleId: 'com.example.flutterEproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoLv3scG3IcTcd0ZYdeFYSHaxhqCbZp7w',
    appId: '1:1086543133004:ios:f56d354c94a598a88cb7e9',
    messagingSenderId: '1086543133004',
    projectId: 'eproject-8a023',
    storageBucket: 'eproject-8a023.firebasestorage.app',
    iosBundleId: 'com.example.flutterEproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIFJmzE7vcjjIGu4WSQFEbLqY43hnHT8',
    appId: '1:1086543133004:web:ae6e7e3170389bf98cb7e9',
    messagingSenderId: '1086543133004',
    projectId: 'eproject-8a023',
    authDomain: 'eproject-8a023.firebaseapp.com',
    storageBucket: 'eproject-8a023.firebasestorage.app',
    measurementId: 'G-TKRV9G1VQ6',
  );
}
